version: '3.8'

services:
  wg-easy:
    image: zw135113/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=X.X.X.X
      - PASSWORD=123456
      - WG_ALLOWED_IPS=10.65.0.0/24
      - WG_MTU=1280
      - WG_DEFAULT_ADDRESS=10.65.0.x
      - WG_DEFAULT_DNS=114.114.114.114
      - WG_PERSISTENT_KEEPALIVE=25
      - PORT=51021
      - WG_PORT=51020
    volumes:
      - /wgvpn/config:/etc/wireguard
    ports:
      - "51020:51020/udp"
      - "51021:51021"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    working_dir: /app
    sysctls:
      - "net.ipv4.conf.all.src_valid_mark=1"
      - "net.ipv4.ip_forward=1"
    restart: unless-stopped
    runtime: runc

